vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
       programmes_images:
           uri_prefix: /upload/programmes
           upload_destination: '%kernel.project_dir%/public/upload/programmes'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
